POST http://fauques.freeboxos.fr:3000/login
Content-Type: application/json

{
  "username": "max"
}

### GET Matches
GET http://fauques.freeboxos.fr:3000/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTA1ZTU0Ni1lZjBhLTQ5MzctOWQ2MS1hYzQxYjVlNTk0NzUiLCJ1c2VybmFtZSI6InRlc3QzIiwiaWF0IjoxNjM4OTYyODIzLCJleHAiOjE2NzA1MjA0MjN9.n2OQsc9ZhdioQ7QdZl-e0NJqQczpotCfKtLySQiP9ds

### GET Match test/test3
GET http://fauques.freeboxos.fr:3000/matches/61b498071053fe731065bc1c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkYWZmMWYyYi0xMDU5LTQwZGQtYjdlMi1jODMzMDE1ZGVlZWIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2MzkyMjQzNDQsImV4cCI6MTY3MDc4MTk0NH0.jUdcZcUSXbCn4927j2YzUSCLL5i7LCwk4M8zbUG-NQk

### GET Match test/test3 Token different
GET http://fauques.freeboxos.fr:3000/matches/61b498071053fe731065bc1c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTA1ZTU0Ni1lZjBhLTQ5MzctOWQ2MS1hYzQxYjVlNTk0NzUiLCJ1c2VybmFtZSI6InRlc3QzIiwiaWF0IjoxNjM4OTYyODIzLCJleHAiOjE2NzA1MjA0MjN9.n2OQsc9ZhdioQ7QdZl-e0NJqQczpotCfKtLySQiP9ds


### POST MATCH test3
POST http://fauques.freeboxos.fr:3000/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTA1ZTU0Ni1lZjBhLTQ5MzctOWQ2MS1hYzQxYjVlNTk0NzUiLCJ1c2VybmFtZSI6InRlc3QzIiwiaWF0IjoxNjM4OTYyODIzLCJleHAiOjE2NzA1MjA0MjN9.n2OQsc9ZhdioQ7QdZl-e0NJqQczpotCfKtLySQiP9ds

### POST MATCH test
POST http://fauques.freeboxos.fr:3000/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkYWZmMWYyYi0xMDU5LTQwZGQtYjdlMi1jODMzMDE1ZGVlZWIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2MzkyMjQzNDQsImV4cCI6MTY3MDc4MTk0NH0.jUdcZcUSXbCn4927j2YzUSCLL5i7LCwk4M8zbUG-NQk


### POST MOVE 1 test3
POST http://fauques.freeboxos.fr:3000/matches/61b494e61053fe731065bbef/turns/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTA1ZTU0Ni1lZjBhLTQ5MzctOWQ2MS1hYzQxYjVlNTk0NzUiLCJ1c2VybmFtZSI6InRlc3QzIiwiaWF0IjoxNjM4OTYyODIzLCJleHAiOjE2NzA1MjA0MjN9.n2OQsc9ZhdioQ7QdZl-e0NJqQczpotCfKtLySQiP9ds

{
  "move": "rock"
}

### POST MOVE 1 test
POST http://fauques.freeboxos.fr:3000/matches/61b494e61053fe731065bbef/turns/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkYWZmMWYyYi0xMDU5LTQwZGQtYjdlMi1jODMzMDE1ZGVlZWIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2MzkyMjQzNDQsImV4cCI6MTY3MDc4MTk0NH0.jUdcZcUSXbCn4927j2YzUSCLL5i7LCwk4M8zbUG-NQk

{
  "move": "rock"
}

### POST MOVE 2 test3
POST http://fauques.freeboxos.fr:3000/matches/61b494e61053fe731065bbef/turns/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTA1ZTU0Ni1lZjBhLTQ5MzctOWQ2MS1hYzQxYjVlNTk0NzUiLCJ1c2VybmFtZSI6InRlc3QzIiwiaWF0IjoxNjM4OTYyODIzLCJleHAiOjE2NzA1MjA0MjN9.n2OQsc9ZhdioQ7QdZl-e0NJqQczpotCfKtLySQiP9ds

{
  "move": "paper"
}

### POST MOVE 2 test
POST http://fauques.freeboxos.fr:3000/matches/61b494e61053fe731065bbef/turns/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkYWZmMWYyYi0xMDU5LTQwZGQtYjdlMi1jODMzMDE1ZGVlZWIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2MzkyMjQzNDQsImV4cCI6MTY3MDc4MTk0NH0.jUdcZcUSXbCn4927j2YzUSCLL5i7LCwk4M8zbUG-NQk

{
  "move": "rock"
}


### POST MOVE 3 test3
POST http://fauques.freeboxos.fr:3000/matches/61b494e61053fe731065bbef/turns/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTA1ZTU0Ni1lZjBhLTQ5MzctOWQ2MS1hYzQxYjVlNTk0NzUiLCJ1c2VybmFtZSI6InRlc3QzIiwiaWF0IjoxNjM4OTYyODIzLCJleHAiOjE2NzA1MjA0MjN9.n2OQsc9ZhdioQ7QdZl-e0NJqQczpotCfKtLySQiP9ds

{
  "move": "paper"
}

### POST MOVE 3 test
POST http://fauques.freeboxos.fr:3000/matches/61b494e61053fe731065bbef/turns/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkYWZmMWYyYi0xMDU5LTQwZGQtYjdlMi1jODMzMDE1ZGVlZWIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2MzkyMjQzNDQsImV4cCI6MTY3MDc4MTk0NH0.jUdcZcUSXbCn4927j2YzUSCLL5i7LCwk4M8zbUG-NQk

{
  "move": "scissors"
}
